### ISSUE TITLE
启动报这个错误

### ISSUE THREAD

**Issue by ppabc** [lfbear/ansible-api#1]
[root@centos6a v2.2.0]# ansible-api
Traceback (most recent call last):
  File "/usr/bin/ansible-api", line 32, in <module>
    from ansible.executor.process.detail import DetailProcess
ImportError: No module named detail
[root@centos6a v2.2.0]#

**Comment by lfbear** [comment]
是使用 v2.2.0/lib/ 中的代码覆盖ansible安装后的lib目录代码 因为修改了ansible官方代码中的某些部分 所以这个操作是必要的

**Comment by lfbear** [comment]
或者使用当前代码中的 python setup.py install
