### ISSUE TITLE
不知道哪里出错了

### ISSUE THREAD

**Issue by lliuxp** [lfbear/ansible-api#11]
{"rc": 0, "detail": {}}
把callback里面的 crucial 类型打印出来是 <class 'ansible.playbook.play.Play'>

**Comment by lliuxp** [comment]
如果目标IP是127.0.0.1 的话是有结果的，换了别的IP就不行了。

**Comment by lfbear** [comment]
May I have more info, such as the contents of playbook and HTTP parameter, still lots of scenes not have been tested at callback plugin
