### ISSUE TITLE
Error: Failed when parsing body as json

### ISSUE THREAD

**Issue by x2y2** [lfbear/ansible-api#23]
uri= /command
data={"n":"test1","m":"command","t":"127.0.0.1","a":"uptime","s":"42e075802d3bfae76cc0f78dfbe34669"}
sign_key = "ansible-api-key"

![image](https://user-images.githubusercontent.com/15082460/64109608-845beb00-cdb2-11e9-80e8-8bc41b7fe6f4.png)
why i get 
Error: Failed when parsing body as json

**Comment by lfbear** [comment]
plase do not use 'application/x-www-form-urlencoded', that's 'form' type, use 'raw' in your screenshot and add this header "Content-Type: application/json"
