### ISSUE TITLE
MD5 should never be used for validation

### ISSUE THREAD

**Issue by jbackman** [lfbear/ansible-api#27]
MD5 (and SHA1) have been marked cryptographically "broken" for a long time (https://www.kb.cert.org/vuls/id/836068).

Proposing https://github.com/lfbear/ansible-api/pull/26 to replace MD5 with SHA256 (but you could update to replace with anything supported in the hashlib)

**Comment by lfbear** [comment]
Fixed in v0.5.1, you can change the encryption in /etc/ansible/api.cfg (sign_mode=sha256)
