### ISSUE TITLE
58行时间是否用本地时间更好？

### ISSUE THREAD

**Issue by ppabc** [lfbear/ansible-api#4]
ansible-api文件
    report = time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()) + ' | ' + str
改为
    report = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime()) + ' | ' + str
58行时间是否用本地时间更好？

**Comment by lfbear** [comment]
多谢提醒 已经修正
fixed
