### ISSUE TITLE
不能在B网段启动吗？

### ISSUE THREAD

**Issue by newbe36524** [lfbear/ansible-api#8]
ansible.cfg

# ==============================================
#         Config file for Ansible-Api
#
#     A restful http api for ansible 2.x
#    I am not a part of ansible official code
# ==============================================

##
# Base configuration part
#
[default]

#listen host
host           = 10.0.200.115
#listen port
port           = 8765
#signature string for api call
sign_key       = YOUR_SIGNATURE_KEY_HERE
#log path if using daemon mode
log_path       = /var/log/ansible-api.log
#ip white list (multiple separated by space, leave a blank for all allowed)
allow_ip       =
#concurrence task number (default:4)
thread_pool_size =

##
# Optional configuration part
# if you wanna use the feature of file managing
#
[directory]
#your playbook path (file *.yml in this dir will be worked)
playbook       = ~
#your script path (file *.sh in this dir will be worked)
script         = ~
#your authkeys path (file */authorized_keys in this dir will be worked)
authkeys       =

其中10.0.200.115的掩码是255.255.0.0

这个ip从外部使用ssh进入没有问题。

启动时出错信息：
Ansible API is running in Debug Mode
Traceback (most recent call last):
  File "/usr/bin/ansible-api", line 32, in <module>
    app = WebApi()
  File "/usr/lib/python2.7/site-packages/ansible_api/webapi.py", line 35, in __init__
    http_server.listen(Config.Get('port'), Config.Get('host'))
  File "/usr/lib64/python2.7/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by lfbear** [comment]
Can not bind your IP and port, check if can be used

**Comment by newbe36524** [comment]
almost two years passed
